# Generated by Django 3.2.2 on 2021-05-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_phone'),
        ('main_seven_strings', '0002_auto_20210513_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectricGuitar',
            new_name='Product',
        ),
    ]
