# Generated by Django 3.2.2 on 2021-05-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_seven_strings', '0003_rename_electricguitar_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Electric Guitar'), (2, 'Acoustic Guitar'), (3, 'Accessories')], default=1, max_length=100),
        ),
    ]
