# Generated by Django 3.2.2 on 2021-05-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_seven_strings', '0004_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcousticGuitar',
        ),
    ]
