# Generated by Django 3.2.2 on 2021-05-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_seven_strings', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Electric Guitar'), ('2', 'Acoustic Guitar'), ('3', 'Accessories')], default='Electric Guitar', max_length=100),
        ),
    ]
