# Generated by Django 3.2.2 on 2021-05-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_seven_strings', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='main_seven_strings/media/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('e_g', 'Electric Guitar'), ('a_g', 'Acoustic Guitar'), ('accessories', 'Accessories')], default='Electric Guitar', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='main_seven_strings/media/<django.db.models.fields.CharField>'),
        ),
    ]
