# Generated by Django 3.2.2 on 2021-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_seven_strings', '0015_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electric Guitar', 'Electric Guitar'), ('Acoustic Guitar', 'Acoustic Guitar'), ('Accessories', 'Accessories')], default='Electric Guitar', max_length=100),
        ),
    ]
